version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - chatbot-network

  # Placeholder for future services
  # database:
  #   image: postgres:13
  #   container_name: chatbot-db
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=chatbot
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - chatbot-network

networks:
  chatbot-network:
    driver: bridge

# volumes:
#   postgres_data:
